### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by fks213** [fks213/laba2#1]
Выполнил:
Ивонин Константин Андреевич ИС-541

Проверил:
@evgeny-p

**Comment by evgeny-p** [comment]
1. Не пишите лишних `else`: [Use Early Exits and continue to Simplify Code](http://llvm.org/docs/CodingStandards.html#use-early-exits-and-continue-to-simplify-code), [Don’t use else after a return](http://llvm.org/docs/CodingStandards.html#don-t-use-else-after-a-return)
1. Понятно, что конфликт был создан в демонстрационных целях, но напоминаю, что в обычной работе не следует выполнять такие мержи.
1. Заголовки коммитов — с заглавной буквы.
1. Часть кода (12−53) написана с лишним отступом.
1. После операторов перед круглой скобкой обычно ставится пробел в соответствии с правилами естественного языка. Вызов функции — математическая запись, пробел перед открывающей круглой скобкой не ставится.

**Comment by fks213** [comment]
Вроде бы все поправил

**Comment by evgeny-p** [comment]
См. отступ в строках 29−30.

**Comment by fks213** [comment]
Не заметил, исправил

**Comment by evgeny-p** [comment]
Принято.
